// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb5wEbDnsDITMekJY90q9uHmVY_uXsRqw',
    appId: '1:1053290126900:web:9aa9e1218f5c51c257b461',
    messagingSenderId: '1053290126900',
    projectId: 'basic-firebase-app-61aa5',
    authDomain: 'basic-firebase-app-61aa5.firebaseapp.com',
    storageBucket: 'basic-firebase-app-61aa5.firebasestorage.app',
    measurementId: 'G-1MN84PEGTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj_7UPDgmHHPakfwZBETPtpcfsGbkDpgQ',
    appId: '1:1053290126900:android:3fbab1d34258348457b461',
    messagingSenderId: '1053290126900',
    projectId: 'basic-firebase-app-61aa5',
    storageBucket: 'basic-firebase-app-61aa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8mMJhSJcvfVdsMwPGrKydxtHPdXnw9_E',
    appId: '1:1053290126900:ios:6ef508b63ce77e1557b461',
    messagingSenderId: '1053290126900',
    projectId: 'basic-firebase-app-61aa5',
    storageBucket: 'basic-firebase-app-61aa5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8mMJhSJcvfVdsMwPGrKydxtHPdXnw9_E',
    appId: '1:1053290126900:ios:6ef508b63ce77e1557b461',
    messagingSenderId: '1053290126900',
    projectId: 'basic-firebase-app-61aa5',
    storageBucket: 'basic-firebase-app-61aa5.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb5wEbDnsDITMekJY90q9uHmVY_uXsRqw',
    appId: '1:1053290126900:web:54055f25e3a9a9e157b461',
    messagingSenderId: '1053290126900',
    projectId: 'basic-firebase-app-61aa5',
    authDomain: 'basic-firebase-app-61aa5.firebaseapp.com',
    storageBucket: 'basic-firebase-app-61aa5.firebasestorage.app',
    measurementId: 'G-KW20SJT76Q',
  );
}
